[package]
name = "libdnscheck"
version = "0.1.0"
authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "~1.0"
dbus = "0.9.1"
dbus-tree = "0.9.0"
libc = "0.2.93"

generate-dbus-resolve1 = { path = "../generate-dbus-resolve1" }
