[package]
name = "libdnscheck"
description = "Checks DNS allow- and deny-lists"
homepage = "https://github.com/andrewaylett/dabl"
readme = "README.md"

repository = "https://github.com/andrewaylett/dabl"
license = "Apache-2.0"

version = "0.2.0"
authors = ["Andrew Aylett <andrew@aylett.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "~1.0"
dbus = "0.9.1"
dbus-tree = "0.9.0"
libc = "0.2.86"

generate-dbus-resolve1 = { path = "../generate-dbus-resolve1", version = "0.2.0" }
