repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.6.0"
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^\.idea
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
  - id: mixed-line-ending
  - id: check-xml
  - id: forbid-submodules
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: "2.7.3"
  hooks:
  - id: editorconfig-checker
    exclude: "(.github|.idea)/.*"
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
    exclude_types:
    - yaml
- repo: local
  hooks:
  - id: cargo-version-update
    name: Check Cargo Versions
    language: docker_image
    entry: docker.io/rust:1.89.0 cargo update -w
    pass_filenames: false
    files: "Cargo\\.(lock|toml)"
- repo: https://github.com/andrewaylett/pre-commit-hooks
  rev: v0.7.0
  hooks:
  - id: init-hooks
  - id: cargo-fmt
  - id: cargo-clippy
  - id: cog

- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.81.5
  hooks:
  - id: renovate-config-validator
    args:
    - --strict
ci:
  skip:
  - cargo-clippy
